name: Publish

on: [push]

jobs:
  publish:
    if: |
      !contains(github.event.head_commit.author.name, 'Automated Version Bump') &&
      !contains(github.event.head_commit.message, 'ci :version') &&
      github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v8.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: 'master'
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@xl8-ai'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
