name: Publish

on: [push]

jobs:
  publish:
    if: |
      !contains(github.event.head_commit.author.name, 'Automated Version Bump') &&
      !contains(github.event.head_commit.message, 'ci :version') &&
      github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v8.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: 'master'
      - run: echo "//npm.pkg.github.com/:_authToken=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" > ~/.npmrc
      - run: npm publish
